export const lightTheme = {
  colors: {
    'base-title': '#272221',
    'base-subtitle': '#403937',
    'base-text': '#574F4D',
    'base-label': '#8D8686',
    'base-hover': '#D7D5D5',
    'base-button': '#E6E5E5',
    'base-input': '#EDEDED',
    'base-card': '#F3F2F2',
    'base-background': '#EDEDED',
    'base-light-color': '#FFFF',
    '1-color': '#1dd3af',
    '2-color': '#bcdd7e',
    '3-color': '#6b4d9b',
    'yellow-color': '#e2f41a',
    'red-color': '#ff0e00',
    'blue-color': '#4982e5',
    'green-color': '#008000',
  },
  fonts: {
    family: {
      primary: '"Roboto", sans-serif',
      secondary: '"Baloo 2", cursive',
    },
    sizes: {
      xxhuge: '4.8rem',
      xhuge: '4.4rem',
      huge: '3.2rem',
      big: '2.4rem',
      medium2: '2rem',
      medium: '1.8rem',
      small4: '1.6rem',
      small3: '1.4rem',
      small2: '1.2rem',
      small: '1rem',
    },
  },
};
